/**
 * Este paquete contiene clases útiles para la herramienta.
 */
package zinbig.item.util;

/**
 * Esta clase se utiliza para definir valores para constantes que se utilizan en
 * la herramienta.
 * 
 * @author Javier Bazzocco javier.bazzocco@zinbig.com
 * 
 */
public class Constants {

	public static final String PROJECTS_COUNT = "PROJECTS_COUNT";

	public static final String OPEN_ITEMS_COUNT = "OPEN_ITEMS_COUNT";

	public static final String PUBLIC_PROJECTS_COUNT = "PUBLIC_PROJECTS_COUNT";

	public static final String MOST_ACTIVE_PROJECT_OID = "MOST_ACTIVE_PROJECT_OID";

	public static final String MOST_ACTIVE_PROJECT_NAME = "MOST_ACTIVE_PROJECT_NAME";

	public static final String DEFAULT_PROJECT = "DEFAULT_PROJECT";

	public static final String PROJECTS_ADMINISTRATION_COLUMN_NAME = "PROJECTS_ADMINISTRATION_COLUMN_NAME";

	public static final String PROJECTS_ADMINISTRATION_COLUMN_ORDER = "PROJECTS_ADMINISTRATION_COLUMN_ORDER";

	public static final String USERS_ADMINISTRATION_COLUMN_NAME = "USERS_ADMINISTRATION_COLUMN_NAME";

	public static final String USERS_ADMINISTRATION_COLUMN_ORDER = "USERS_ADMINISTRATION_COLUMN_ORDER";

	public static final String USERS_GROUPS_ADMINISTRATION_COLUMN_ORDER = "USERS_GROUPS_ADMINISTRATION_COLUMN_ORDER";

	public static final String USERS_GROUPS_ADMINISTRATION_COLUMN_NAME = "USERS_GROUPS_ADMINISTRATION_COLUMN_NAME";

	public static final String PRIORITY_SETS_ADMINISTRATION_COLUMN_NAME = "PRIORITY_SETS_ADMINISTRATION_COLUMN_NAME";

	public static final String PRIORITY_SETS_ADMINISTRATION_COLUMN_ORDER = "PRIORITY_SETS_ADMINISTRATION_COLUMN_ORDER";

	public static final String ITEMS_ADMINISTRATION_COLUMN_NAME = "ITEMS_ADMINISTRATION_COLUMN_NAME";

	public static final String ITEMS_ADMINISTRATION_COLUMN_ORDER = "ITEMS_ADMINISTRATION_COLUMN_ORDER";

	public static final String PRIORITIES_ADMINISTRATION_COLUMN_NAME = "PRIORITIES_ADMINISTRATION_COLUMN_NAME";

	public static final String PRIORITIES_ADMINISTRATION_COLUMN_ORDER = "PRIORITIES_ADMINISTRATION_COLUMN_ORDER";

	public static final String MOST_INTERESTING_ITEM_ID = "MOST_INTERESTING_ITEM_ID";

	public static final String MOST_INTERESTING_ITEM_OID = "MOST_INTERESTING_ITEM_OID";

	public static final String VIEW_PROJECTS_COLUMN_NAME = "VIEW_PROJECTS_COLUMN_NAME";

	public static final String VIEW_PROJECTS_COLUMN_ORDER = "VIEW_PROJECTS_COLUMN_ORDER";

	public static final String ITEM_TYPES_ADMINISTRATION_COLUMN_NAME = "ITEM_TYPES_ADMINISTRATION_COLUMN_NAME";

	public static final String ITEM_TYPES_ADMINISTRATION_COLUMN_ORDER = "ITEM_TYPES_ADMINISTRATION_COLUMN_ORDER";

	public static final String MANAGE_PRIORITIES_COLUMN_NAME = "MANAGE_PRIORITIES_COLUMN_NAME";

	public static final String MANAGE_PRIORITIES_COLUMN_ORDER = "MANAGE_PRIORITIES_COLUMN_ORDER";

	public static final String MANAGE_WORKFLOW_LINK_DESCRIPTIONS_COLUMN_NAME = "MANAGE_WORKFLOW_LINK_DESCRIPTIONS_COLUMN_NAME";

	public static final String MANAGE_WORKFLOW_LINK_DESCRIPTIONS_COLUMN_ORDER = "MANAGE_WORKFLOW_LINK_DESCRIPTIONS_COLUMN_ORDER";

	public static final String MANAGE_ITEM_TYPES_COLUMN_NAME = "MANAGE_ITEM_TYPES_COLUMN_NAME";

	public static final String MANAGE_ITEM_TYPES_COLUMN_ORDER = "MANAGE_ITEM_TYPES_COLUMN_ORDER";

	public static final String UPDATE_TIME = "UPDATE_TIME";

	public static final String ITEMS_COUNT = "ITEMS_COUNT";

	public static final String USERS_COUNT = "USERS_COUNT";

	public static final String SCHEDULER = "SCHEDULER";

	public static final String MOST_ACTIVE_USER_1 = "MOST_ACTIVE_USER_1";

	public static final String MOST_ACTIVE_USER_2 = "MOST_ACTIVE_USER_2";

	public static final String MOST_ACTIVE_USER_3 = "MOST_ACTIVE_USER_3";

	public static final String MANAGE_WORKFLOW_NODE_DESCRIPTIONS_COLUMN_NAME = "MANAGE_WORKFLOW_NODE_DESCRIPTIONS_COLUMN_NAME";

	public static final String MANAGE_WORKFLOW_NODE_DESCRIPTIONS_COLUMN_ORDER = "MANAGE_WORKFLOW_NODE_DESCRIPTIONS_COLUMN_ORDER";

	public static final String MANAGE_PROPERTIES_COLUMN_NAME = "MANAGE_PROPERTIES_COLUMN_NAME";

	public static final String MANAGE_PROPERTIES_COLUMN_ORDER = "MANAGE_PROPERTIES_COLUMN_ORDER";

}
